### ISSUE TITLE
Maksukortin arvo voi olla int tai float

### ISSUE THREAD

**Issue by TemeKoo** [ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io#34]
https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io/blob/888280e51f94c8b8eb840c5e777210689a636f35/materiaali/python/viikko2.md?plain=1#L261-L287

Tässä luokan `Maksukortti` muuttuja `arvo` voi olla tyyppiä `int` tai `float`. Tästä seuraa, että jos maksukortilla on arvoa esimerkiksi 5 euroa, voi `__str__` metodi palauttaa joko `"Kortilla on rahaa 5 euroa"` tai `"Kortilla on rahaa 5.0 euroa"`, riippuen kumpaa tyyppiä muuttuja on.

**Comment by Kaltsoon** [comment]
Kiitokset, ongelma on korjattu!
