### ISSUE TITLE
Viikon 6 materiaalissa sama osio kahteen kertaan

### ISSUE THREAD

**Issue by rikurauhala** [ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io#45]
Viikon 6 Python-materiaalissa toistuu kahteen kertaan koodikatselmointiin liittyvän osuuden alku. Ongelma on ilmeisesti siinä, että sama tieto haetaan myös koodikatselmointi.md-tiedostosta, mutta samoja tekstirivejä ei ole poistettu viikko6.md-tiedostosta.

https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io/blob/12d66fb0b4916a92a1962efe3549264ad2db7fc0/materiaali/python/viikko6.md?plain=1#L138

**Comment by Kaltsoon** [comment]
Kiitokset tiedosta, nyt on korjattu!
